---
version: "3"

tasks:
  switch:
    desc: "Switching to new NixOs configuration"
    vars:
      HOST:
        sh: printf '%s\n' nixos wsl | fzf --prompt="Select host> "
    cmds:
      - echo 'Switching to new NixOs configuration ({{.HOST}})'
      - nixos-rebuild switch --flake .#{{.HOST}}
    silent: false

  build:
    desc: "Building new NixOs configuration"
    vars:
      HOST:
        sh: printf '%s\n' nixos wsl | fzf --prompt="Select host> "
    cmds:
      - echo 'Building new NixOs configuration ({{.HOST}})'
      - nixos-rebuild build --flake .#{{.HOST}}
    silent: false

  boot:
    desc: "Boot to new NixOs configuration"
    cmds:
      - echo 'Boot to new NixOs configuration'
      - nixos-rebuild boot --flake .
    silent: false

  test:
    desc: "Test new NixOs configuration"
    vars:
      HOST:
        sh: printf '%s\n' nixos wsl | fzf --prompt="Select host> "
    cmds:
      - echo 'Test new NixOs configuration ({{.HOST}})'
      - nixos-rebuild test --flake .#{{.HOST}}
    silent: false

  upgrade:
    desc: "Upgrade to new NixOs configuration"
    vars:
      HOST:
        sh: printf '%s\n' nixos wsl | fzf --prompt="Select host> "
    cmds:
      - echo 'Upgrade to new NixOs configuration ({{.HOST}})'
      - nixos-rebuild switch --upgrade --flake .#{{.HOST}}
    silent: false

  channel-update:
    desc: "Update nix channels"
    cmds:
      - nix-channel --update
    silent: false

  flake-update:
    desc: "Update flakes"
    cmds:
      - nix flake update
    silent: false

  clean:
    desc: "Clean up old nix generations"
    cmds:
      - nix-collect-garbage -d --delete-older-than 3d
    silent: false

  format:
    desc: "Format NixOS configuration files"
    cmds:
      - find . -name '*.nix' -exec nixfmt {} +
    silent: false

  symlink:
    desc: "Symlink nixos-config to /etc/nixos"
    cmds:
      - echo 'Symlinking configuration.nix'
      - ln -sfn ~/nixos-config/ /etc/nixos/
    silent: false

  channel-add:
    desc: "Adding channels"
    cmds:
      - nix-channel --add https://nixos.org/channels/nixos-25.05 nixos
    silent: false
